spring.datasource.url = jdbc:postgresql://localhost:5430/demoDB
spring.datasource.username=usr
spring.datasource.password=pwd
spring.flyway.enabled = true
spring.datasource.driverclassname = org.postgresql.Driver

spring.jpa.hibernate.ddl-auto = create-drop
logging.level.org.springframework = debug
spring.jpa.generate-ddl=true

